server.port: 8080
# 应用名称
spring:
  application:
    name: scaffold
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbc-url: jdbc:mysql://127.0.0.1:3306/mytest?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    username: root
    password: root
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 60000
      pool-name: DatebookHikariCP
      max-lifetime: 1765000
      connection-timeout: 30000
      maxLifetimeximumPoolSize: 20
      connection-test-query: SELECT 1
# 指定Mybatis的实体目录
mybatis:
  type-aliases-package: com.tool.scaffold.common.pojo.domain



