# 应用名称
spring:
  application:
    name: scaffold
server.port: 8080

#下面这些内容是为了让MyBatis映射
#指定Mybatis的Mapper文件
mybatis.mapper-locations: classpath:mybatis/mappers/*.xml
#指定Mybatis的实体目录
mybatis.type-aliases-package: com.tool.scaffold.common.pojo.domain
